### PR TITLE
Changed Environments to setdefault

### PR DESCRIPTION
**Pull request by pizzapanther**
I changed environmental variables to `setdefault` so that you can override them. Right now you can't override them.

### CODE REVIEW

**Comment by MechanisM** [comment]
With your changes, you've also modified package version in __init__.py and info in setup.py.

**Comment by pizzapanther** [comment]
Yes I changed it so I could publish a change I needed.  I didn't know if this was still maintained. I'll put it back so it can be merged.

**Comment by pizzapanther** [comment]
Ok I've updated the `init` and `setup`.  Note I also included an update to restrict permissions to the admin view. See #15. Let me know if you want that out or not.

**Comment by MechanisM** [comment]
Thanks @pizzapanther !

**Comment by pizzapanther** [comment]
Thanks for the merge when do you think this will go out on PyPi?

Just FYI, I'm using django-uwsgi in https://pypi.python.org/pypi/djzen/17.6.4

It's a simpler way to setup django projects, and I pre-packaged django-uwsgi in so you can deploy out of the box. I'll update to the latest django-uwsgi whenever it comes out.

**Comment by MechanisM** [comment]
Hey! Thanks again, django-uwsgi just published to pypi https://pypi.org/project/django-uwsgi/

**Comment by MechanisM** [comment]
@pizzapanther btw why do you using whitenoise with uwsgi? uwsgi itself can serve static files much faster than whitenoise
for example some section in my uwsgi.ini
```
[staticfiles]
static-gzip-all
static-map2 = /assets=%dpublic
static-map2 = /uploads=%dpublic
```

**Comment by pizzapanther** [comment]
I saw that but didn't know how well it worked so I went with what I knew and used in the past.  But I'll definitely check it out.

**Pull request merged**
